export function globalCss():string
export function sudokuText():string
export function sudokuInput():string
export function sudokuCellBothThick():string
export function sudokuCellBottomThick():string
export function sudokuCellRightThick():string
export function sudokuCell():string
export function sudokuTable():string
export function footer():string
export function h2s():string
export function card():string
export function mainS():string
export function navLink():string
export function nav():string
export function titleS():string
export function header():string
export function page():string
